substitutions:
  device_name: "h-esp-pzem-power-01"
  friendly_name: "Power Monitor 01"
  device_comment: "Dual Phase Energy Monitor"
  version: "25.12.31.1"
  
  uart_tx_pin: GPIO21
  uart_rx_pin: GPIO20
  update_interval: "10s"
  
  addr_phase_a: "1"
  addr_phase_b: "2"

esphome:
  name: ${device_name}
  comment: ${device_comment}
  on_boot:
    priority: -10
    then:
      - lambda: |-
          id(v_l1).publish_state(0);
          id(p_l1).publish_state(0);
          id(v_l2).publish_state(0);
          id(p_l2).publish_state(0);
          id(total_power).publish_state(0);

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: esp-idf

api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.local
  ap:
    ssid: "${device_name}_ap"
    password: !secret ssid_password

web_server:
  port: 80

time:
  - platform: homeassistant
    id: ha_time
    on_time:
      - seconds: 59
        minutes: 59
        hours: 23
        days_of_week: SUN
        then:
          - sensor.template.publish:
              id: total_weekly_energy
              state: 0

logger:
  level: INFO

uart:
  id: uart_bus
  tx_pin: ${uart_tx_pin}
  rx_pin: ${uart_rx_pin}
  baud_rate: 9600
  stop_bits: 1

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
  - platform: template
    name: "Uptime"
    id: uptime_human
    icon: mdi:clock-start

sensor:
  # --- PHASE L1 ---
  - platform: pzemac
    id: pzem_l1
    address: ${addr_phase_a}
    update_interval: ${update_interval}
    voltage:
      name: "${friendly_name} L1 Voltage"
      id: v_l1
      filters:
        - lambda: "return (x > 300.0) ? NAN : x;"
        - timeout: { timeout: 25s, value: 0 }
    power:
      name: "${friendly_name} L1 Power"
      id: p_l1
      filters:
        - lambda: "return (x > 25000.0) ? NAN : x;"
        - timeout: { timeout: 25s, value: 0 }
    energy:
      name: "${friendly_name} L1 Energy"
      id: e_l1
      unit_of_measurement: "kWh"  
      accuracy_decimals: 3        
      device_class: energy
      state_class: total_increasing
      filters:
        - lambda: "return (x > 1000000.0) ? NAN : x;" 
        - multiply: 0.001

  # --- PHASE L2 ---
  - platform: pzemac
    id: pzem_l2
    address: ${addr_phase_b}
    update_interval: ${update_interval}
    voltage:
      name: "${friendly_name} L2 Voltage"
      id: v_l2
      filters:
        - lambda: "return (x > 300.0) ? NAN : x;"
        - timeout: { timeout: 25s, value: 0 }
    power:
      name: "${friendly_name} L2 Power"
      id: p_l2
      filters:
        - lambda: "return (x > 25000.0) ? NAN : x;"
        - timeout: { timeout: 25s, value: 0 }
    energy:
      name: "${friendly_name} L2 Energy"
      id: e_l2
      unit_of_measurement: "kWh"  
      accuracy_decimals: 3        
      device_class: energy
      state_class: total_increasing
      filters:
        - lambda: "return (x > 1000000.0) ? NAN : x;" 
        - multiply: 0.001

  # --- TOTALS ---
  - platform: template
    name: "${friendly_name} Total Power"
    unit_of_measurement: "W"
    id: total_power
    state_class: measurement
    device_class: power
    lambda: |-
      float p1 = id(p_l1).state;
      float p2 = id(p_l2).state;
      if (std::isnan(p1)) p1 = 0.0f;
      if (std::isnan(p2)) p2 = 0.0f;
      return p1 + p2;
    update_interval: ${update_interval}

  - platform: total_daily_energy
    name: "${friendly_name} Total Weekly Energy"
    id: total_weekly_energy
    power_id: total_power
    unit_of_measurement: "kWh"
    accuracy_decimals: 3
    icon: mdi:calendar-range
    # Note: No multiply filter here, total_daily_energy handles W to kWh automatically.
  
  - platform: internal_temperature
    name: "${friendly_name} MCU Temperature"
    unit_of_measurement: "°C"
    update_interval: 60s

  - platform: uptime
    id: uptime_sensor
    internal: true
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(x);
              int days = seconds / (24 * 3600);
              int hours = (seconds % (24 * 3600)) / 3600;
              int minutes = (seconds % 3600) / 60;
              return ((days ? to_string(days) + "d " : "") +
                     (hours ? to_string(hours) + "h " : "") +
                     (minutes ? to_string(minutes) + "m " : "")).c_str();

button:
  - platform: template
    name: "${friendly_name} L1 Reset Energy"
    on_press:
      - pzemac.reset_energy: id: pzem_l1
          
  - platform: template
    name: "${friendly_name} L2 Reset Energy"
    on_press:
      - pzemac.reset_energy: id: pzem_l2

  - platform: restart
    name: "ESP Reboot"
