# Use this config ONLY for changing the PZEM address.
# Connect ONLY ONE PZEM module at a time.
# IMPORTANT: 220V AC must be connected to the PZEM during this process!

substitutions:
  uart_tx_pin: GPIO21 # D6
  uart_rx_pin: GPIO20 # D7

esphome:
  name: "pzem-address-changer"

esp32:
  board: seeed_xiao_esp32c3
  framework: { type: esp-idf }

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.local
  ap:
    ssid: "${device_name}_ap"
    password: !secret ssid_password

web_server:
  port: 80

logger:
  level: DEBUG

uart:
  id: uart_bus
  tx_pin: ${uart_tx_pin}
  rx_pin: ${uart_rx_pin}
  baud_rate: 9600

button:
  - platform: template
    name: "Set PZEM Address to 2"
    icon: "mdi:chip"
    on_press:
      lambda: |-
        // Modbus RTU: [Broadcast 00][Write 06][Reg 00 02][Value 00 02][CRC E8 0B]
        uint8_t cmd[8] = {0x00, 0x06, 0x00, 0x02, 0x00, 0x02, 0xE8, 0x0B};
        id(uart_bus).write_array(cmd, 8);
        ESP_LOGI("PZEM_FIX", "Command to set address 2 sent!");
